### ISSUE TITLE
Build error on Buster, Pi4 w/ Bluez 5.52

### ISSUE THREAD

**Issue by okyeron** [RuckerGauge/blePeripheral#3]
Attempting to test your blePeripheral but I can't build the project. I followed your Bluez 5.50 instructions for installing node.

I'm running Bluez 5.52

Any guidance based on the following errors?

```
make: *** [abstract_socket.target.mk:109: Release/obj.target/abstract_socket/src/abstract_socket.o] Error 1
make: Leaving directory '/home/we/blePeripheral/node_modules/abstract-socket/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.66-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/we/blePeripheral/node_modules/abstract-socket
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@2.0.0 (node_modules/abstract-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@2.0.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

up to date in 4.169s
fixed 0 of 1 vulnerability in 26 scanned packages
  1 vulnerability required manual review and could not be updated
10.0.1.21 ~/blePeripheral $ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Sensitive Data Exposure                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ put                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ dbus-native                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ dbus-native > put                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1007                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

versions
```
10.0.1.21 ~/blePeripheral $ node -v
v12.16.1
10.0.1.21 ~/blePeripheral $ npm -v
6.13.4
```

**Comment by JohnRucker** [comment]
If your running this on a Pi update to their latest OS version and you won’t have to update to BlueZ 5.x.x as it is now included in the native build.

**Comment by okyeron** [comment]
Can’t upgrade the OS on this device. 

I’m building the most recent Bluez to enable midi over Bluetooth. 

However - The errors above seem wholly node related though - not involving Bluez at all.

**Comment by JohnRucker** [comment]
Humm haven’t seen that error.  Wonder if it has something to do with Node v12 you appear to be using.  I’m using v10.18 but plan on migrating to the latest build once I get caught up.

**Comment by JohnRucker** [comment]
Hey I didn't catch you were using Bluetooh ver 5.52.  This has only been tested with version 5.50 as that is the current version that ships Raspbian Buster Lite.
