### ISSUE TITLE
Advertising a secondary service

### ISSUE THREAD

**Issue by gaurav-Lilly** [RuckerGauge/blePeripheral#8]
While i am trying to register a secondary service i am getting an error 
```Swift
Error calling RegisterAdvertisement method.
Error calling RegisterAdvertisement method. DBusError: Maximum advertisements reached
    at new DBusError (/home/pi/DIGH_LITT_Cerberus-cerberusAdvertising/node_modules/dbus/lib/error.js:9:9)
    at createError (/home/pi/DIGH_LITT_Cerberus-cerberusAdvertising/node_modules/dbus/lib/bus.js:243:9) {
  dbusName: 'org.bluez.Error.NotPermitted'
}
/home/pi/DIGH_LITT_Cerberus-cerberusAdvertising/node_modules/dbus/lib/service.js:15
		var iface = self.objects[objectPath]['interfaces'][interfaceName];
		                                    ^

TypeError: Cannot read property 'interfaces' of undefined
    at module.exports.<anonymous> (/home/pi/DIGH_LITT_Cerberus-cerberusAdvertising/node_modules/dbus/lib/service.js:15:39)
    at module.exports.emit (events.js:315:20)
    at /home/pi/DIGH_LITT_Cerberus-cerberusAdvertising/node_modules/dbus/lib/dbus.js:25:16

Any idea what is happening here ?

**Comment by JohnRucker** [comment]
It looks like you're getting an error when your class starts and tries to advertise.  Only your primary service can register an advertisement.  When you construct the blePeripheral for secondary classes set PrimaryService to false.  Here is an example of how I do it [`this.bPrl = new BLEperipheral(this.config.dBusName, this.config.uuid, this._bleConfig, false);`](https://github.com/WallGauge/appManager/blob/3f5c851a1d664bb7d4d85fae2fbc9672f62c80c0/appManagerClass.js#L76). The false at the end will start a secondary class with no advertising.

**Comment by gaurav-Lilly** [comment]
Thanks for the response John.
What i am trying to achieve here is to advertise more than one service(say one is primary service and other will be secondary).So if i go by your solution, i am not seeing the other service on my iOS device.Only Primary service with characteristics are visible. Any idea how to achieve that ? or am i missing something here?

**Comment by gaurav-Lilly** [comment]
After trying your suggestions, i am getting this error now:
```Swift
gattServiceClass.js | __________________________________________________________________
GAURAV---->/com/cerberusdeviceinfo
/home/pi/DIGH_LITT_Cerberus-cerberusAdvertising/node_modules/dbus/lib/service.js:16
		var iface = self.objects[objectPath]['interfaces'][interfaceName];
		                                    ^

TypeError: Cannot read property 'interfaces' of undefined
    at module.exports.<anonymous> (/home/pi/DIGH_LITT_Cerberus-cerberusAdvertising/node_modules/dbus/lib/service.js:16:39)
    at module.exports.emit (events.js:315:20)
    at /home/pi/DIGH_LITT_Cerberus-cerberusAdvertising/node_modules/dbus/lib/dbus.js:25:16
```

**Comment by gaurav-Lilly** [comment]
Let me explain in detail , what i am trying here for better understanding:
Objective: 
a)To advertise my Raspberry PI as a peripheral and appear in the list of scanned device by CENTRAL iOS app.
b) After selecting the device in the scanned list , i should be able to see, two services and their characteristics
c) I am able to see a service when declared as primary and its characteristics.The above error comes, when i try to create another service and characteristics(with 'primary' parameter as 'false'.
How i am doing it :
a) In my primary service class, i am doing like this:
 ```Swift
        var secondaryService = require('./secondaryservice')
          // Then inside primary service connection change
              blePrimaryService.on('ConnectionChange', (connected) =>  {
                secondaryService = new secondaryService()
            }
```
// my secondaryService.js is same like sampleApp.js
after this if i run the primary service:
i get the above error of 'interfaces'

Let me know if this explanation makes  sense. Do share your thoughts here. I checked all your repos, but could not find the classes which are initialising the blePeripheral:
this.bPrl = new BLEperipheral(this.config.dBusName, this.config.uuid, this._bleConfig, false);

**Comment by JohnRucker** [comment]
Each secondary class has to be its own standalone node application with a unique dbus configuration.  You may want to take a look at AppManager https://github.com/WallGauge/appManager. It might be the missing piece in the examples you have been looking at.
